competition_attempt_factors: [0.87, 0.95, 1.0]

lifts:
  - name: Muscle Up
    abbreviation: MU
    bodyweight_coefficient: 0.85
    rounding_increment: 1.25
    training_max_factor: 0.87
  - name: Pull Up
    abbreviation: PU
    bodyweight_coefficient: 0.95
    rounding_increment: 1.25
    training_max_factor: 0.87
  - name: Dip
    abbreviation: D
    bodyweight_coefficient: 0.85
    rounding_increment: 1.25
    training_max_factor: 0.87
  - name: Squat
    abbreviation: SQ
    bodyweight_coefficient: 0.25
    rounding_increment: 2.5
    training_max_factor: 0.87

program_weeks:
  - "5":
      - scaling_factors: [0.65, 0.75, 0.85]
      - reps_per_set: [5, 5, 5]
  - "3":
      - scaling_factors: [0.70, 0.80, 0.90]
      - reps_per_set: [3, 3, 3]
  - "1":
      - scaling_factors: [0.75, 0.85, 0.95]
      - reps_per_set: [5, 3, 1]
  - "deload":
      - scaling_factors: [0.40, 0.50, 0.60]
      - reps_per_set: [5, 5, 5]

zero_weight_strictness: 0.4